# Site Data
title: "Ruff Management"
tagline: " — Investor Relations"
name: "Ruff Management Inc."
author_bio:
  "We are Ruff Management Inc., an organization passionate about agile development and efficient utilization of time."
description: "Ruff Management Inc. is a management company which manages other firms and raises equity."
footer_description:
  'The phrase "digital garden" is a metaphor for thinking about writing and creating that focuses less on the
  resulting "showpiece" and more on the process, care, and craft it takes to get there. While not everybody
  has or works in a dirt garden, we all share a familiarity with the idea of what a garden is.'
notes_url: "https://ir.ruff-manage.com"
profile_pic: "https://blazed.sirv.com/ruff-manage.com/ruff-lion.png"
favicon: https://blazed.sirv.com/ruff-manage.com/ruff-lion.png?w=64&h=64
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ir.ruff-manage.com/" # the base hostname & protocol for your site, e.g. https://example.com
theme_color: white
encoding: utf-8

# Links and Social Media
donate_link: https://opencollective.com/blazed-dev
repository: https://github.com/ruff-org/investor
github: https://github.com/ruff-org
twitter: https://twitter.com/RuffManage
portfolio: https://blz.one/products/
email: hello@ruff-manage.com

# Build Settings
theme: null
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-minifier
  - jekyll-toc

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
  smart_quotes: ["apos", "apos", "quot", "quot"]
  syntax_highlighter: rouge

sass:
  style: compressed

JEKYLL_ENV: "production"

collections:
  notes:
    output: true
    permalink: /notes/:title
  journals:
    output: true
    permalink: /journals/:title
  pages:
    output: true
    permalink: /page/:name

disqus:
  shortname: journalbar

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /posts/:title
      content-type: post
      category: "Post"
      toc: true
  - scope:
      path: ""
      type: notes
    values:
      layout: post
      content-type: notes
  - scope:
      path: ""
      type: journals
    values:
      layout: post
      content-type: journals
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      content-type: pages

jekyll-archives:
  enabled: []
  layout: default
  permalinks:
    year: "/:year/"
    month: "/:year/:month/"
    day: "/:year/:month/:day/"
    tag: "/tag/:name/"
    category: "/category/:name/"

toc:
  min_level: 1
  max_level: 6
  ordered_list: false
  no_toc_section_class: no-toc
  list_class: section-nav
  sublist_class: ""
  item_class: entry
  item_prefix: toc-
